spring.application.name=task-service
server.port = 8081

spring.datasource.url=jdbc:postgresql://localhost:5432/task_service_db
spring.datasource.username=vinaynaugain
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

node-service.url=http://localhost:8000
